name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 mypy pytest-cov

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Confirm CI setup success
      run: echo "GitHub Actions CI pipeline is running successfully"

    - name: Show Python version
      run: python --version

    - name: Lint with flake8
      run: flake8 src/ tests/

    - name: Run tests with pytest
      run: pytest --cov=src tests/

    - name: Upload coverage report for testing coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: .coverage
